#!/usr/bin/env bash
# Commercial security gate for ponyllm.
#
# This gate is intentionally fail-closed: it requires explicit, reviewable evidence
# for every commercial security claim. A missing command, fixture, or evidence file
# is a failure. It is a checklist runner, not a claim that security has passed.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
readonly EVIDENCE_DIR="$PROJECT_ROOT/.security-evidence"
readonly TRUST_DIR="$PROJECT_ROOT/scripts/commercial/trust"
readonly RUNNER="$PROJECT_ROOT/scripts/commercial/security-integration-test"
readonly PUBLIC_KEY="$TRUST_DIR/release-evidence.pub"
readonly SIGNATURE_VERIFIER="$PROJECT_ROOT/scripts/commercial/verify-evidence-signature"

failures=0
checks=0
readonly RUN_NONCE="$(date +%s)-$$"

fail() {
  failures=$((failures + 1))
  printf 'FAIL: %s\n' "$1" >&2
}

check() {
  checks=$((checks + 1))
  local name="$1"
  local evidence="$2"
  local current_revision
  current_revision="$(git -C "$PROJECT_ROOT" rev-parse HEAD 2>/dev/null || true)"
  if [[ -n "$evidence" && -s "$evidence" && ! -L "$evidence" ]] \
      && case "$evidence" in "$EVIDENCE_DIR"/*) true ;; *) false ;; esac \
      && grep -Eq '^(status=pass|result[[:space:]]*=[[:space:]]*PASS)$' "$evidence" \
      && grep -Eq "^tested_revision=${current_revision}$" "$evidence" \
      && grep -Eq "^run_nonce=${RUN_NONCE}$" "$evidence" \
      && grep -Eq '^command_exit=0$' "$evidence" \
      && grep -Eq '^coverage=[^[:space:]]+$' "$evidence" \
      && grep -Eq '^attestation=[^[:space:]]+$' "$evidence"; then
    printf 'EVIDENCE REQUIRED/PRESENT: %s (%s)\n' "$name" "$evidence"
  else
    fail "$name (structured PASS evidence must be workspace-local, revision-bound, command_exit=0, covered, and attested: ${evidence:-<path not supplied>})"
  fi
}

printf '=== ponyllm commercial security gate (fail-closed) ===\n'
printf 'Project: %s\n' "$PROJECT_ROOT"
printf 'Evidence: %s\n' "$EVIDENCE_DIR"
printf '%s\n' 'This run reports requirements; it does not certify security.'

# Only the repository-owned runner may generate this run's evidence. It receives
# a nonce and revision, and must fail closed when any matrix is incomplete.
current_revision="$(git -C "$PROJECT_ROOT" rev-parse HEAD 2>/dev/null || true)"
source_digest="$(git -C "$PROJECT_ROOT" ls-files -co --exclude-standard -z | sort -z | xargs -0 -r sha256sum | sha256sum | awk '{print $1}')"
[[ -n "$current_revision" && -n "$source_digest" ]] || fail 'source revision/digest cannot be computed'
[[ -x "$RUNNER" ]] || fail "repository-owned security runner missing: $RUNNER"
if (( failures == 0 )); then
  if ! SECURITY_EVIDENCE_DIR="$EVIDENCE_DIR" SECURITY_RUN_NONCE="$RUN_NONCE" SECURITY_TESTED_REVISION="$current_revision" "$RUNNER"; then
    fail 'repository-owned security runner failed'
  fi
fi

# The evidence contract is deliberately explicit. Each artifact must be generated
# and reviewed by the owning team; this script does not infer a pass from source text.
check 'admin/tenant authorization matrix: admin versus tenant versus anonymous, every endpoint and method' \
  "$EVIDENCE_DIR/auth-matrix.md"
check 'model grant and IDOR tests: cross-tenant model IDs, grants, revocation, enumeration, and deny-by-default' \
  "$EVIDENCE_DIR/model-grant-idor.md"
check 'SSRF and egress controls: private/link-local/metadata IPs, DNS rebinding, redirects, schemes, ports, and allowlist' \
  "$EVIDENCE_DIR/ssrf-egress.md"
check 'response/header hardening: redirect handling, hop-by-hop headers, host forwarding, cookie/token leakage' \
  "$EVIDENCE_DIR/redirect-headers.md"
check 'redaction and secret scans: logs, traces, errors, telemetry, fixtures, source, and build artifacts' \
  "$EVIDENCE_DIR/redaction-secret-scan.md"
check 'public liveness versus commercial readiness: unauthenticated health semantics cannot imply tenant/API readiness' \
  "$EVIDENCE_DIR/liveness-commercial-readiness.md"
check 'OAuth callback code/state expiry, replay, and token-query rejection matrix' \
  "$EVIDENCE_DIR/oauth-token-query.md"
check 'backup secret scan: backups, snapshots, archives, crash dumps, and restore media contain no live credentials' \
  "$EVIDENCE_DIR/backup-secret-scan.md"

# Evidence is generated by a repository-owned runner and cryptographically signed;
# caller-authored files or environment overrides are not accepted.
[[ -x "$RUNNER" ]] || fail "repository-owned security runner missing: $RUNNER"
[[ -f "$PUBLIC_KEY" && ! -L "$PUBLIC_KEY" ]] || fail "trusted evidence public key missing: $PUBLIC_KEY"
[[ -x "$SIGNATURE_VERIFIER" ]] || fail "repository-owned signature verifier missing: $SIGNATURE_VERIFIER"
if [[ -d "$EVIDENCE_DIR" && ! -L "$EVIDENCE_DIR" ]]; then
  manifest="$EVIDENCE_DIR/manifest.sha256"
  signature="$EVIDENCE_DIR/manifest.sig"
  if [[ -f "$manifest" && ! -L "$manifest" && -f "$signature" && ! -L "$signature" && -x "$SIGNATURE_VERIFIER" ]]; then
    if ! (cd "$EVIDENCE_DIR" && sha256sum --check --strict "$(basename "$manifest")"); then
      fail 'security evidence manifest does not verify'
    fi
    if ! "$SIGNATURE_VERIFIER" --public-key "$PUBLIC_KEY" --manifest "$manifest" --signature "$signature"; then
      fail 'security evidence signature is not cryptographically valid'
    fi
    grep -Eq "^source_digest=${source_digest}$" "$EVIDENCE_DIR/attestation.sha256" || fail 'attestation source digest does not match current tracked source'
    grep -Eq '^build_digest=[a-f0-9]{64}$' "$EVIDENCE_DIR/attestation.sha256" || fail 'attestation lacks build digest'
    expires_at="$(sed -n 's/^expires_at=//p' "$EVIDENCE_DIR/attestation.sha256" | head -n1)"
    [[ "$expires_at" =~ ^[0-9]+$ ]] && (( expires_at > $(date +%s) )) || fail 'attestation is expired or malformed'
    grep -Fxq 'attestation.sha256' "$manifest" || fail 'signed manifest omits attestation.sha256'
    grep -Fxq 'attestation.sig' "$manifest" || fail 'signed manifest omits attestation.sig'
  else
    fail 'signed security evidence manifest, signature, and attestation are required'
  fi
else
  fail 'security evidence directory'
fi

printf 'Checks evaluated: %d\n' "$checks"
printf 'Failures: %d\n' "$failures"
if (( failures != 0 )); then
  printf 'SECURITY GATE: NOT PASSED (fail-closed; review and evidence required)\n' >&2
  exit 1
fi

# A signed, repository-generated attestation is required; an environment ACK is
# intentionally ignored because callers must not self-authorize release.
attestation="$EVIDENCE_DIR/attestation.sha256"
if [[ ! -s "$attestation" || -L "$attestation" ]] || ! grep -Eq '^reviewer=[^[:space:]]+$' "$attestation" || ! grep -Eq '^tested_revision=[^[:space:]]+$' "$attestation" || ! grep -Eq '^signature=[^[:space:]]+$' "$attestation"; then
  fail 'signed reviewer attestation with reviewer, tested_revision and signature is required'
fi
if (( failures != 0 )); then
  printf 'SECURITY GATE: NOT PASSED (fail-closed; structured evidence/attestation required)\n' >&2
  exit 1
fi
printf 'SECURITY GATE: structured evidence and signed reviewer attestation supplied; deployment scope still requires review.\n'
exit 0
