#!/usr/bin/env bash
#
# gen-favicon.sh — 从 web/public/favicon.svg 重新生成真实多尺寸 favicon.ico，
#                 并同步刷新 deploy/ponyllm-favicon.yaml（ConfigMap 唯一事实源）。
#
# 输出:
#   - web/public/favicon.ico      16/32/48 三尺寸、PNG 压缩条目的 ICO
#                                 （Vista+ 格式，现代浏览器全兼容，产物入库）
#   - deploy/ponyllm-favicon.yaml data.favicon.svg + binaryData.favicon.ico
#
# 依赖:
#   - headless Chromium/Chrome（可用 CHROMIUM_BIN 覆盖查找路径）
#   - python3 + Pillow
#
# 用法: scripts/gen-favicon.sh [svg-path] [out-path]
# 任何一步失败以非零退出；退出前校验产物结构（ICO magic / 条目数 / PNG 签名）。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-$ROOT/web/public/favicon.svg}"
OUT="${2:-$ROOT/web/public/favicon.ico}"
CONFIGMAP="${3:-$ROOT/deploy/ponyllm-favicon.yaml}"

[ -f "$SRC" ] || { echo "错误: 源 SVG 不存在: $SRC" >&2; exit 1; }

# --- 定位 headless Chromium -------------------------------------------------
CHROMIUM_BIN="${CHROMIUM_BIN:-}"
if [ -z "$CHROMIUM_BIN" ]; then
  for c in google-chrome google-chrome-stable chromium chromium-browser; do
    if command -v "$c" >/dev/null 2>&1 && "$c" --version >/dev/null 2>&1; then
      # 跳过 snap 占位符等"存在但运行即失败"的二进制（--version 探测兜底）
      CHROMIUM_BIN="$c"
      break
    fi
  done
fi
[ -n "$CHROMIUM_BIN" ] || { echo "错误: 未找到可用的 headless Chromium（可设置 CHROMIUM_BIN）" >&2; exit 1; }

python3 -c "import PIL" 2>/dev/null || { echo "错误: python3 缺少 Pillow" >&2; exit 1; }

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# `readlink -f` 是 GNU-only（macOS 会失败），用 python realpath 保证可移植。
SVG_ABS="$(python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$SRC")"
cat > "$TMPDIR/render.html" <<HTML
<!doctype html>
<html>
<head><meta charset="utf-8"><style>html,body{margin:0;padding:0;background:transparent}img{display:block}</style></head>
<body><img src="file://$SVG_ABS" width="512" height="512"></body>
</html>
HTML

render() { # $1 = extra chrome args (--headless mode)
  # shellcheck disable=SC2086
  "$CHROMIUM_BIN" $1 --disable-gpu --hide-scrollbars \
    --default-background-color=00000000 --force-device-scale-factor=1 \
    --window-size=512,512 --screenshot="$TMPDIR/favicon-512.png" \
    "file://$TMPDIR/render.html" >/dev/null 2>&1
}

render "--headless=new" || render "--headless" || render "--headless --no-sandbox" || {
  echo "错误: Chromium 渲染 SVG 失败" >&2; exit 1;
}
[ -s "$TMPDIR/favicon-512.png" ] || { echo "错误: 截图产物为空" >&2; exit 1; }

# --- Pillow 缩放打包 + 结构校验（非零退出即失败）---------------------------
python3 - "$TMPDIR/favicon-512.png" "$OUT" <<'PY'
import struct, sys
from PIL import Image

png_path, out_path = sys.argv[1], sys.argv[2]
im = Image.open(png_path).convert("RGBA")
assert im.size == (512, 512), f"截图尺寸异常: {im.size}"
sizes = [(16, 16), (32, 32), (48, 48)]
im.save(out_path, format="ICO", sizes=sizes)

data = open(out_path, "rb").read()
assert data[:4] == b"\x00\x00\x01\x00", "产物不是 ICO（magic 错误）"
count = struct.unpack("<H", data[4:6])[0]
assert count == len(sizes), f"ICO 条目数异常: {count} != {len(sizes)}"
png_entries = 0
for i in range(count):
    entry = data[6 + 16 * i: 6 + 16 * (i + 1)]
    size = struct.unpack("<I", entry[8:12])[0]   # dwBytesInRes
    off = struct.unpack("<I", entry[12:16])[0]   # dwImageOffset
    payload = data[off:off + 4]
    assert payload == b"\x89PNG" or payload == b"BM", f"条目 {i} 既非 PNG 也非 BMP"
    if payload == b"\x89PNG":
        png_entries += 1
# Pillow 对带 alpha 的 RGBA 图写 PNG 压缩条目、对不透明图写 BMP 条目；
# 下面的"全部 PNG"断言隐含前提：源图标必须带透明通道（当前 PonyLogo 即如此）。
assert png_entries == count, f"存在非 PNG 压缩条目: {png_entries}/{count}"
print(f"OK: {out_path}（{len(data)} bytes, {count} 条目, 全部 PNG 压缩）")
PY

# --- 同步刷新 deploy/ponyllm-favicon.yaml（ConfigMap 唯一事实源）-----------
python3 - "$SRC" "$OUT" "$CONFIGMAP" <<'PY'
import base64, sys

svg_path, ico_path, cm_path = sys.argv[1], sys.argv[2], sys.argv[3]
svg_text = open(svg_path, encoding="utf-8").read().rstrip("\n")
ico_b64 = base64.b64encode(open(ico_path, "rb").read()).decode("ascii")
indented = "\n".join("    " + line for line in svg_text.split("\n"))
yaml = f"""# AUTO-GENERATED by scripts/gen-favicon.sh — 不要手改。
# favicon 内容的唯一事实源：改图标 = 改 web/public/favicon.svg → 重跑脚本 →
# 提交本文件 + web/public/favicon.ico。部署顺序：先 apply 本清单，再 apply
# ponyllm-deployment.yaml（其 subPath volumeMount 引用同名 ConfigMap）。
apiVersion: v1
kind: ConfigMap
metadata:
  name: ponyllm-favicon
  namespace: ponyllm
  labels:
    app.kubernetes.io/name: ponyllm
data:
  favicon.svg: |
{indented}
binaryData:
  favicon.ico: {ico_b64}
"""
open(cm_path, "w", encoding="utf-8").write(yaml)
print(f"OK: {cm_path}（favicon.svg {len(svg_text)} chars + binaryData ico {len(ico_b64)} b64 chars）")
PY
